language: java
notifications:
  email:
    recipients:
      - alex638000@gmail.com
      - ir.prikhodko@gmail.com
      - pafkan1993@gmail.com
      - ududenko.s98@gmail.com
    on_success: always
    on_failure: always
